name: Tests
on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install tools
        run: python -m pip install --upgrade pip pytest
      
      - name: Install pandas
        run: python -m pip install pandas
      
      - name: Install sqlalchemy
        run: python -m pip install sqlalchemy
      
      - name: Install requests
        run: python -m pip install requests
      
      - name: Install coverage
        run: python -m pip install coverage

      - name: Test with unittest
        run: |
          python3 -m unittest recipe_test.py
          
      - name: Check code coverage
        run: |
          python3 -m coverage run -m unittest recipe_test.py
          python3 -m coverage report
          python3 -m coverage html

      - name: Archive code coverage HTML report
        uses: actions/upload-artifact@v2
        with:
           name: code-coverage-report
           path: htmlcov
